// Auto-generated by pipeline — do not edit manually
export const GAMES = [
  {
    id: 1,
    name: "Red Dead Redemption 2",
    clip: "/clips/1174180.mp4",
    steamAppId: 1174180,
    answers: ["Red Dead Redemption 2", "Unturned", "Don't Starve Together", "War Thunder"]
  },
  {
    id: 2,
    name: "Baldur's Gate 3",
    clip: "/clips/1086940.mp4",
    steamAppId: 1086940,
    answers: ["Don't Starve Together", "PAYDAY 2", "Satisfactory", "Baldur's Gate 3"]
  },
  {
    id: 3,
    name: "PUBG: BATTLEGROUNDS",
    clip: "/clips/578080.mp4",
    steamAppId: 578080,
    answers: ["Paladins\u00ae", "Terraria", "War Thunder", "PUBG: BATTLEGROUNDS"]
  },
  {
    id: 4,
    name: "Terraria",
    clip: "/clips/105600.mp4",
    steamAppId: 105600,
    answers: ["PAYDAY 2", "Dying Light", "Path of Exile", "Terraria"]
  },
  {
    id: 5,
    name: "Rocket League\u00ae",
    clip: "/clips/252950.mp4",
    steamAppId: 252950,
    answers: ["7 Days to Die", "Left 4 Dead 2", "Rocket League\u00ae", "Project Zomboid"]
  },
  {
    id: 6,
    name: "Among Us",
    clip: "/clips/945360.mp4",
    steamAppId: 945360,
    answers: ["Terraria", "Among Us", "Dead by Daylight", "Unturned"]
  },
  {
    id: 7,
    name: "Stardew Valley",
    clip: "/clips/413150.mp4",
    steamAppId: 413150,
    answers: ["Grim Dawn", "Don't Starve Together", "NBA 2K20", "Stardew Valley"]
  },
  {
    id: 8,
    name: "PAYDAY 2",
    clip: "/clips/218620.mp4",
    steamAppId: 218620,
    answers: ["Warframe", "Phasmophobia", "Euro Truck Simulator 2", "PAYDAY 2"]
  },
  {
    id: 9,
    name: "ELDEN RING",
    clip: "/clips/1245620.mp4",
    steamAppId: 1245620,
    answers: ["Monster Hunter Wilds", "PAYDAY 2", "Baldur's Gate 3", "ELDEN RING"]
  }
];
